<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'brand_id' => 1, // Dulux
                'category_id' => 1, // Interior Paint
                'product_code' => 'DLX-INT-001',
                'product_name' => 'Dulux Interior Matte White',
                'description' => 'Sơn nội thất cao cấp mờ dành cho tường và trần nhà. Độ phủ tuyệt vời và độ bền cao.',
                'paint_base' => 'Water-based',
                'finish_type' => 'Matte',
                'volume' => '5L',
                'coverage_area' => '60-70 sqm',
                'cost_price' => 625000,
                'price' => 900000,
                'stock_quantity' => 100,
                'low_stock_alert' => 10,
                'image_url' => 'images/products/chong-tham-dulux-weathershield-y65-20kg.jpg',
                'rating_avg' => 4.5,
                'total_sold' => 150,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'brand_id' => 2, // Nippon Paint
                'category_id' => 2, // Exterior Paint
                'product_code' => 'NP-EXT-002',
                'product_name' => 'Nippon WeatherShield Exterior Gloss',
                'description' => 'Sơn ngoại thất bóng chống chịu thời tiết. Bảo vệ tốt trong điều kiện thời tiết khắc nghiệt.',
                'paint_base' => 'Oil-based',
                'finish_type' => 'Gloss',
                'volume' => '4L',
                'coverage_area' => '45-55 sqm',
                'cost_price' => 750000,
                'price' => 1075000,
                'stock_quantity' => 80,
                'low_stock_alert' => 8,
                'image_url' => 'images/products/sl_2.jpg',
                'rating_avg' => 4.2,
                'total_sold' => 120,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'brand_id' => 3, // Jotun
                'category_id' => 1,
                'product_code' => 'JT-INT-003',
                'product_name' => 'Jotun Lady Supreme Semi-Gloss',
                'description' => 'Sơn nội thất bán bóng sang trọng với lớp hoàn thiện vượt trội và dễ thi công.',
                'paint_base' => 'Water-based',
                'finish_type' => 'Semi-Gloss',
                'volume' => '3L',
                'coverage_area' => '35-40 sqm',
                'cost_price' => 500000,
                'price' => 725000,
                'stock_quantity' => 90,
                'low_stock_alert' => 9,
                'image_url' => 'images/products/200689.png',
                'rating_avg' => 4.7,
                'total_sold' => 200,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'brand_id' => 1,
                'category_id' => 3, // Primer
                'product_code' => 'DLX-PRM-004',
                'product_name' => 'Dulux Primer Sealer',
                'description' => 'Lớp lót cao cấp giúp sơn bám dính tốt hơn và độ phủ cao hơn.',
                'paint_base' => 'Water-based',
                'finish_type' => 'Primer',
                'volume' => '2.5L',
                'coverage_area' => '25-30 sqm',
                'cost_price' => 375000,
                'price' => 500000,
                'stock_quantity' => 70,
                'low_stock_alert' => 7,
                'image_url' => 'images/products/chat-chong-tham-dulux-aquatech-flex-waterproofing.jpg',
                'rating_avg' => 4.0,
                'total_sold' => 80,
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'brand_id' => 2,
                'category_id' => 1,
                'product_code' => 'NP-INT-005',
                'product_name' => 'Nippon Odorless Interior Paint',
                'description' => 'Sơn nội thất không mùi lý tưởng cho phòng ngủ và khu vực sinh hoạt.',
                'paint_base' => 'Water-based',
                'finish_type' => 'Matte',
                'volume' => '1L',
                'coverage_area' => '12-15 sqm',
                'cost_price' => 200000,
                'price' => 325000,
                'stock_quantity' => 150,
                'low_stock_alert' => 15,
                'image_url' => 'images/products/odl_bst_2.jpg',
                'rating_avg' => 4.3,
                'total_sold' => 95,
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'brand_id' => 3,
                'category_id' => 2,
                'product_code' => 'JT-EXT-006',
                'product_name' => 'Jotun Temacoat Exterior Acrylic',
                'description' => 'Sơn ngoại thất acrylic bền bỉ với khả năng chống chịu thời tiết xuất sắc.',
                'paint_base' => 'Acrylic',
                'finish_type' => 'Matte',
                'volume' => '10L',
                'coverage_area' => '100-120 sqm',
                'cost_price' => 1250000,
                'price' => 1750000,
                'stock_quantity' => 50,
                'low_stock_alert' => 5,
                'image_url' => 'images/products/129395.png',
                'rating_avg' => 4.6,
                'total_sold' => 75,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'brand_id' => 1,
                'category_id' => 1,
                'product_code' => 'DLX-INT-007',
                'product_name' => 'Dulux Wash & Wear Kitchen Paint',
                'description' => 'Sơn chuyên dụng cho bếp, dễ lau chùi và chống bám bẩn.',
                'paint_base' => 'Water-based',
                'finish_type' => 'Semi-Gloss',
                'volume' => '2L',
                'coverage_area' => '20-25 sqm',
                'cost_price' => 450000,
                'price' => 625000,
                'stock_quantity' => 110,
                'low_stock_alert' => 11,
                'image_url' => 'images/products/son-dulux-easyclean-chong-bam-ban.jpg',
                'rating_avg' => 4.4,
                'total_sold' => 110,
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'brand_id' => 2,
                'category_id' => 3,
                'product_code' => 'NP-PRM-008',
                'product_name' => 'Nippon Anti-Rust Primer',
                'description' => 'Lớp lót chống gỉ cho bề mặt kim loại.',
                'paint_base' => 'Oil-based',
                'finish_type' => 'Primer',
                'volume' => '1L',
                'coverage_area' => '10-12 sqm',
                'cost_price' => 300000,
                'price' => 425000,
                'stock_quantity' => 60,
                'low_stock_alert' => 6,
                'image_url' => 'images/products/matex_smdm_2.jpg',
                'rating_avg' => 3.9,
                'total_sold' => 45,
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'brand_id' => 3,
                'category_id' => 1,
                'product_code' => 'JT-INT-009',
                'product_name' => 'Jotun Multicolor Interior Paint',
                'description' => 'Sơn nội thất đổi màu mang lại hiệu ứng độc đáo cho không gian nội thất.',
                'paint_base' => 'Water-based',
                'finish_type' => 'Pearl',
                'volume' => '2.5L',
                'coverage_area' => '25-30 sqm',
                'cost_price' => 550000,
                'price' => 800000,
                'stock_quantity' => 40,
                'low_stock_alert' => 4,
                'image_url' => 'images/products/200687.png',
                'rating_avg' => 4.8,
                'total_sold' => 30,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'brand_id' => 1,
                'category_id' => 2,
                'product_code' => 'DLX-EXT-010',
                'product_name' => 'Dulux Weathershield Roof Paint',
                'description' => 'Sơn mái nhà chuyên dụng cho khả năng bảo vệ lâu dài.',
                'paint_base' => 'Acrylic',
                'finish_type' => 'Matte',
                'volume' => '20L',
                'coverage_area' => '200-250 sqm',
                'cost_price' => 2000000,
                'price' => 2750000,
                'stock_quantity' => 25,
                'low_stock_alert' => 3,
                'image_url' => 'images/products/son-lot-dulux-trong-nha-a934.jpg',
                'rating_avg' => 4.1,
                'total_sold' => 20,
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'brand_id' => 2,
                'category_id' => 1,
                'product_code' => 'NP-INT-011',
                'product_name' => 'Nippon Eco-Friendly Paint',
                'description' => 'Sơn nội thất thân thiện với môi trường với hàm lượng VOC thấp.',
                'paint_base' => 'Water-based',
                'finish_type' => 'Eggshell',
                'volume' => '5L',
                'coverage_area' => '55-65 sqm',
                'cost_price' => 280000,
                'price' => 389000,
                'stock_quantity' => 85,
                'low_stock_alert' => 8,
                'image_url' => 'images/products/virusguard_0.jpg',
                'rating_avg' => 4.5,
                'total_sold' => 65,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'brand_id' => 3,
                'category_id' => 3,
                'product_code' => 'JT-PRM-012',
                'product_name' => 'Jotun Wood Primer',
                'description' => 'Lớp lót chuyên dụng cho bề mặt gỗ để tăng độ bám dính của sơn.',
                'paint_base' => 'Oil-based',
                'finish_type' => 'Primer',
                'volume' => '2L',
                'coverage_area' => '18-22 sqm',
                'cost_price' => 160000,
                'price' => 240000,
                'stock_quantity' => 75,
                'low_stock_alert' => 7,
                'image_url' => 'images/products/200692.png',
                'rating_avg' => 4.2,
                'total_sold' => 55,
                'is_featured' => false,
                'is_active' => true,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
